import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body> <div className="flex min-h-screen bg-slate-50">
  <aside className="w-56 bg-slate-900 text-slate-300 flex flex-col">
    <div className="px-5 py-5 border-b border-slate-800">
      <div className="text-white font-semibold text-sm tracking-wide">GRAVITAS ONE</div>
      <div className="text-xs text-slate-500 mt-0.5">Realitní OS · beta</div>
    </div>
    <nav className="flex-1 py-3">
      <Link
        href="/"
        className="flex items-center gap-2 px-5 py-2.5 text-sm hover:bg-slate-800 hover:text-white"
      >
        Dashboard
      </Link>
      <Link
        href="/kalkulacka"
        className="flex items-center gap-2 px-5 py-2.5 text-sm hover:bg-slate-800 hover:text-white"
      >
        Kalkulačka
      </Link>
    </nav>
  </aside>
  <div className="flex-1">{children}</div>
</div></body>
    </html>
  );
}
